### ISSUE TITLE
Problems importing dmk tools

### ISSUE THREAD

**Issue by crhoff** [Danielaleite/Nextrout#3]
Hi there,

I'm having some issues importing the dmk tools. I ran `setup.py` and noticed that I had the folder nextrout_core but not otp_utilities. When I try to run `test.py`, I receive the following output:

`ModuleNotFoundError: No module named 'dmk'`

After manually installing dmk with pip, I receive:

`ImportError: cannot import name 'Dmkcontrols' from 'dmk' `

Any suggestions on how to resolve this would be appreciated, thank you kindly!

**Comment by Danielaleite** [comment]
Dear @crhoff ,

thanks for reporting the issue. I believe the problem is that you will have to manually install the dmk module (it doesn't work with pip). You can try doing:

`os.system('mkdir ../dmk_utilities')
repos_list = ['dmk_solver','globals', 'linear_algebra','p1galerkin','geometry']
for repo in repos_list: os.system('cd ../dmk_utilities && git clone https://gitlab.com/enrico_facca/'+repo+'.git')
`

at the same level as the nextrout_core folder. Let me know if that works.
